### ISSUE TITLE
Better handling of product attributes

### ISSUE THREAD

**Issue by madc** [thelia/thelia#2316] opened 2016-12-02 10:49 UTC
Thelia v2.3.3

Currently there are two way offered to create product attributes:
- Create all manually
- Use the combination builder

This may work fine, if you have only a couple of possibility. But we have a product with three selectable attributes, each holding a couple of options. This leaves us with a couple of hundred possibilities, where the price and similar fields need to be set manually.
This is especially annoying, combined with #2314, when you have to manually reset the price after the sale tool didn't do it.

**Comment by roadster31** [comment] 2016-12-02 13:00
Duplicate of #1600 

The [LegacyProductAttributes](https://github.com/thelia-modules/LegacyProductAttributes) is offering a solution to this problem.

**Closed by roadster31** 2016-12-02 13:00 UTC
