### ISSUE TITLE
Problem at installation

### ISSUE THREAD

**Issue by guillaum3f** [thelia/thelia#1440] opened 2015-05-21 00:33 UTC
I was trying to help someone who tried to install thelia.
This person got stuck on the installation of db. 

**The error message is** : 
`PDOException in PdoConnection.php line 47:
SQLSTATE[28000] [1045] Access denied for user 'm5zgqaja'@'www-004.vlan-102.olympe.in' (using password: YES)`

**The problem is** :

`at PDO->__construct('mysql:host=sql2.olympe.in;dbname=m5zgqaja;port=3306', 'm5zgqaja', '1336332', array('SET NAMES 'UTF8''))` in *PdoConnection.php* line **47**

**Where** : `1336332` is NOT the password this person put in the password field previously... 
*(on the other hand, username and database name are the same string, it's normal)*

**However** in `local/config/database.yml` the mentioned user found that the good password (and good user as well) was recorded. But he can NOT connect to thelia, which redirect to index_dev.php with the error.

I did test on a virtual machin and was able to install the soft and to reproduce the error. On my side, it was easily resolved by modifying data in `local/config/database.yml`. But it does NOT work in the case of the mentioned user. 

I am just lost. Someone has a clue on what's happening here?

**User is able to successfully pass this step** : 
![capture d ecran 2015-05-20 a 16 25 40](https://cloud.githubusercontent.com/assets/12534077/7739662/59c52b38-ff65-11e4-90d9-2a2e9ac42979.png)
**and even this step** : 
![capture d ecran 2015-05-20 a 16 51 18](https://cloud.githubusercontent.com/assets/12534077/7739669/66c5013c-ff65-11e4-9736-02d44afab80b.png)

**Error appears after this step** : 
![1403232c49_690x444](https://cloud.githubusercontent.com/assets/12534077/7739649/18829cf0-ff65-11e4-8ea7-20211fa349a4.png)

**Whole Error**
![capture d ecran 2015-05-21 a 02 25 25](https://cloud.githubusercontent.com/assets/12534077/7739420/b6dc08dc-ff60-11e4-8c13-f02307fbfcc0.png)
![capture d ecran 2015-05-21 a 02 25 33](https://cloud.githubusercontent.com/assets/12534077/7739421/b6ffe7fc-ff60-11e4-9c58-a7c1a82a1ae2.png)

**Comment by roadster31** [comment] 2015-05-21 05:31
What are the steps to reproduce the problem ?

**Comment by guillaum3f** [comment] 2015-05-21 12:19
Basically : installing Thelia, like a beginner does, on [olympe.in](https://www.olympe.in) free hosting environment (runs ubuntu and everything needed by Thelia as the mentioned user has been able to access to the 3rd and 4th installation steps ). I have not much on this, was hoping you already heard about kinda story :/

**Comment by roadster31** [comment] 2015-05-21 12:29
PDO seems to be a problem at olympe.in : https://www.google.fr/search?q=pdo+olympe

**Comment by guillaum3f** [comment] 2015-05-21 12:54
I have setup a testing account. It's against the CGU, then I'll delete it at the end, but I would like to understand what's going on. I have downloaded the last release [here](http://thelia.net) and configure the ftp like this :

**Comment by guillaum3f** [comment] 2015-05-21 16:20
Can't tell. My brother, [with whom I temporarily share the same email/ip address has a nor-eCommerce-neither-testing projet](https://www.olympe.in/on/documents/Olympe-CGS-FR.pdf)  involving Thelia. He has setup an Olympe space account where I have downloaded for him the last release [found here](http://thelia.net). I've also configured the host as following :

***filesystem***
**host** : ftp.olympe.in
**user** : thelia2
**pass** : azerty

*Note : Olympe FTP bandwidth is very badass, transferts are pain in the ass.
Fortunately SCP is available, it uses the same address ftp.olympe.in.
However, because of the poor QoS, some files could be missing...*

***database*** 
**host** : sql2.olympe.in
**dbname** : l5hm5oi1
**user** : l5hm5oi1
**pass** : azerty

***web*** 
**url** : [thelia2.olympe.in](http://thelia2.olympe.in)
**installation page** : 

I launched the installation. But I get stuck for... another reason :'( :'( :'(
![capture d ecran 2015-05-21 a 18 18 24](https://cloud.githubusercontent.com/assets/12534077/7753477/fdbd9916-ffe5-11e4-8263-a5eb5ad1d9ec.png)


**Install Thelia on this host appears to be a challenge...**
Would you give it a try? 

[***Bonus*** *: as I just noticed you may be french speaker (Toulouse), I join the initial in-french discussion about the issue.*](http://community.olympe.in/t/probleme-installation-thelia-et-database/8708/29)

**Comment by roadster31** [comment] 2015-05-21 16:48
It seems to be an olympe.in related problem, please see http://thelia.net/forum/viewtopic.php?pid=65496#p65496 and http://thelia.net/forum/viewtopic.php?pid=61894#p61894

**Comment by guillaum3f** [comment] 2015-05-21 17:00
Maybe some file errors during transfer. I'll look that asap

**Comment by lunika** [comment] 2015-05-25 07:17
can I close this issue ?

**Closed** 2015-05-27 09:00 UTC
