### ISSUE TITLE
Free text product features not localized

### ISSUE THREAD

**Issue by sb-relaxt-at** [thelia/thelia#1617] opened 2015-08-06 11:14 UTC
If you create a product feature without specifying values, you can enter free text for a product feature at each product. This text can not be localized (in contrast to almost any other part of Thelia). You can only enter one text that will show up for all languages.

**Comment by roadster31** [comment] 2015-08-06 11:37
This issue is a duplicate of #401, and is fixed in 2.2.

**Comment by sb-relaxt-at** [comment] 2015-08-06 11:44
Oh, I overlooked this other issue, sorry. Thanks a lot for the fast reply!

**Closed** 2015-08-06 14:36 UTC
